// =============================================================================
// Beacon MVP — Match Service
// =============================================================================
import { PostgrestError } from '@supabase/supabase-js';
import { supabase } from '../lib/supabase';
import {
  MatchRow,
  ConnectionRequestRow,
  MutualMatchResult,
} from '../types/database';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ListMatchesResult {
  data: MatchRow[];
  error: PostgrestError | null;
}

export interface MatchWithProfile {
  id: string;
  event_id: string;
  other_user_id: string;
  other_name: string | null;
  other_role: string | null;
  other_one_liner: string | null;
  other_is_premium: boolean;
  created_at: string;
}

export interface SendConnectionRequestResult {
  request: ConnectionRequestRow | null;
  match: MatchRow | null;
  error: PostgrestError | { message: string } | null;
}

export interface PostEventSummaryInput {
  eventName: string;
  userName: string;
  matches: Array<{
    matchedUserName: string | null;
    matchedUserRole: string | null;
    matchedAt: string; // ISO timestamp
  }>;
}

// ─── Service Functions ────────────────────────────────────────────────────────

/**
 * Count outgoing connection requests this user has sent in an event.
 * Feeds the PresenceEngine momentum score.
 */
export async function countSentConnectionRequests(
  eventId: string,
  requesterId: string
): Promise<number> {
  const { count, error } = await supabase
    .from('connection_requests')
    .select('id', { count: 'exact', head: true })
    .eq('event_id', eventId)
    .eq('requester_id', requesterId);
  if (error) {
    console.error('[match.service] countSentConnectionRequests error:', error);
    return 0;
  }
  return count ?? 0;
}

/**
 * List all matches for a user within a given event, ordered by most recent first.
 */
export async function listMatches(
  eventId: string,
  userId: string
): Promise<ListMatchesResult> {
  const { data, error } = await supabase
    .from('matches')
    .select('*')
    .eq('event_id', eventId)
    .or(`user_a_id.eq.${userId},user_b_id.eq.${userId}`)
    .order('created_at', { ascending: false });

  return { data: data ?? [], error };
}

/**
 * List matches for a user in an event, joined with the other user's profile.
 * Returns plain rows (not the {data, error} envelope) for direct list rendering.
 */
export async function listMatchesWithProfiles(
  eventId: string,
  userId: string
): Promise<MatchWithProfile[]> {
  const { data, error } = await supabase
    .from('matches')
    .select('id, event_id, user_a_id, user_b_id, created_at, user_a:users!matches_user_a_id_fkey(name, role, one_liner, is_premium), user_b:users!matches_user_b_id_fkey(name, role, one_liner, is_premium)')
    .eq('event_id', eventId)
    .or(`user_a_id.eq.${userId},user_b_id.eq.${userId}`)
    .order('created_at', { ascending: false });
  if (error) {
    console.error('[match.service] listMatchesWithProfiles error:', error);
    return [];
  }
  return (data ?? []).map((row: any) => {
    const isA = row.user_a_id === userId;
    const other = isA ? row.user_b : row.user_a;
    return {
      id: row.id,
      event_id: row.event_id,
      other_user_id: isA ? row.user_b_id : row.user_a_id,
      other_name: other?.name ?? null,
      other_role: other?.role ?? null,
      other_one_liner: other?.one_liner ?? null,
      other_is_premium: !!other?.is_premium,
      created_at: row.created_at,
    };
  });
}

/**
 * Generate a plain-text post-event summary email stub.
 *
 * Pure deterministic function — no Supabase call, no external network request.
 * Useful for previewing the email content before sending via a backend function.
 */
export function getPostEventSummaryStub(input: PostEventSummaryInput): string {
  const { eventName, userName, matches } = input;
  const matchCount = matches.length;

  const greeting = `Hi ${userName || 'there'},`;

  const intro =
    matchCount === 0
      ? `Thanks for attending ${eventName}! You didn't make any mutual connections this time — but your profile is ready for the next event.`
      : `Thanks for attending ${eventName}! You made ${matchCount} mutual connection${matchCount === 1 ? '' : 's'}.`;

  const matchLines = matches
    .map((m, i) => {
      const name = m.matchedUserName ?? 'Someone';
      const role = m.matchedUserRole ? ` (${m.matchedUserRole})` : '';
      const date = new Date(m.matchedAt).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
      });
      return `  ${i + 1}. ${name}${role} — matched on ${date}`;
    })
    .join('\n');

  const body =
    matchCount > 0
      ? `\nYour connections:\n${matchLines}\n\nReach out while the event is still fresh!`
      : '';

  const footer = `\nThis summary was generated by Beacon. You received this because you attended ${eventName}.\n`;

  return [greeting, '', intro, body, footer].join('\n');
}
/**
 * Create a connection request from requester → recipient and, if there's
 * already a reciprocal pending request, record a mutual match.
 */
export async function sendConnectionRequest(
  eventId: string,
  requesterId: string,
  recipientId: string
): Promise<SendConnectionRequestResult> {
  // 1) Insert connection request
  const { data: request, error: requestError } = await supabase
    .from('connection_requests')
    .insert({
      event_id: eventId,
      requester_id: requesterId,
      recipient_id: recipientId,
    })
    .select('*')
    .single();

  if (requestError || !request) {
    return {
      request: null,
      match: null,
      error: requestError ?? { message: 'Failed to send connection request.' },
    };
  }

  // 2) Check for mutual match via RPC (may or may not create a row)
  const { data: rpcResult, error: rpcError } = await supabase
    .rpc('detect_mutual_match', {
      p_event_id: eventId,
      p_requester_id: requesterId,
      p_recipient_id: recipientId,
    })
    .returns<MutualMatchResult[]>();

  if (rpcError) {
    // Request succeeded, but we couldn't determine match state.
    // Surface as non-fatal: the UI will just show "Sent".
    return {
      request,
      match: null,
      error: null,
    };
  }

  const mutualMatch = Array.isArray(rpcResult) && rpcResult.length > 0
    ? (rpcResult[0] as MatchRow)
    : null;

  return {
    request,
    match: mutualMatch,
    error: null,
  };
}
