// =============================================================================
// Beacon MVP — Match Service
// =============================================================================
import { PostgrestError } from '@supabase/supabase-js';
import { supabase } from '../lib/supabase';
import { MatchRow } from '../types/database';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ListMatchesResult {
  data: MatchRow[];
  error: PostgrestError | null;
}

export interface PostEventSummaryInput {
  eventName: string;
  userName: string;
  matches: Array<{
    matchedUserName: string | null;
    matchedUserRole: string | null;
    matchedAt: string; // ISO timestamp
  }>;
}

// ─── Service Functions ────────────────────────────────────────────────────────

/**
 * List all matches for a user within a given event, ordered by most recent first.
 */
export async function listMatches(
  eventId: string,
  userId: string
): Promise<ListMatchesResult> {
  const { data, error } = await supabase
    .from('matches')
    .select('*')
    .eq('event_id', eventId)
    .or(`user_a_id.eq.${userId},user_b_id.eq.${userId}`)
    .order('created_at', { ascending: false });

  return { data: data ?? [], error };
}

/**
 * Generate a plain-text post-event summary email stub.
 *
 * Pure deterministic function — no Supabase call, no external network request.
 * Useful for previewing the email content before sending via a backend function.
 */
export function getPostEventSummaryStub(input: PostEventSummaryInput): string {
  const { eventName, userName, matches } = input;
  const matchCount = matches.length;

  const greeting = `Hi ${userName || 'there'},`;

  const intro =
    matchCount === 0
      ? `Thanks for attending ${eventName}! You didn't make any mutual connections this time — but your profile is ready for the next event.`
      : `Thanks for attending ${eventName}! You made ${matchCount} mutual connection${matchCount === 1 ? '' : 's'}.`;

  const matchLines = matches
    .map((m, i) => {
      const name = m.matchedUserName ?? 'Someone';
      const role = m.matchedUserRole ? ` (${m.matchedUserRole})` : '';
      const date = new Date(m.matchedAt).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
      });
      return `  ${i + 1}. ${name}${role} — matched on ${date}`;
    })
    .join('\n');

  const body =
    matchCount > 0
      ? `\nYour connections:\n${matchLines}\n\nReach out while the event is still fresh!`
      : '';

  const footer = `\nThis summary was generated by Beacon. You received this because you attended ${eventName}.\n`;

  return [greeting, '', intro, body, footer].join('\n');
}

export function sendConnectionRequest(eventId: string, requesterId: string, recipientId: string): { request: any; match: any; error: any; } | PromiseLike<{ request: any; match: any; error: any; }> {
  throw new Error('Function not implemented.');
}
