// =============================================================================
// Beacon MVP — Match Service
// =============================================================================
import { PostgrestError } from '@supabase/supabase-js';
import { supabase } from '../lib/supabase';
import type { MatchRow, ConnectionRequestRow } from '../types/database';

export interface ListMatchesResult {
  data: MatchRow[];
  error: PostgrestError | null;
}

export interface MatchWithProfile {
  id: string;
  event_id: string;
  other_user_id: string;
  other_name: string | null;
  other_role: string | null;
  other_one_liner: string | null;
  other_is_premium: boolean;
  created_at: string;
}

export interface SendConnectionRequestResult {
  request: ConnectionRequestRow | null;
  match: MatchRow | null;
  remainingSignalBudget?: number;
  error: PostgrestError | { message: string } | null;
}

export interface PostEventSummaryInput {
  eventName: string;
  userName: string;
  matches: Array<{
    matchedUserName: string | null;
    matchedUserRole: string | null;
    matchedAt: string;
  }>;
}

interface SecureConnectionResultRow {
  request_id: string;
  request_event_id: string;
  requester_id: string;
  recipient_id: string;
  request_status: ConnectionRequestRow['status'];
  request_created_at: string;
  match_id: string | null;
  match_event_id: string | null;
  match_user_a_id: string | null;
  match_user_b_id: string | null;
  match_created_at: string | null;
  remaining_signal_budget: number;
}

function createIdempotencyNonce(): string {
  const randomA = Math.random().toString(36).slice(2);
  const randomB = Math.random().toString(36).slice(2);
  return `signal-${Date.now().toString(36)}-${randomA}${randomB}`.slice(0, 120);
}

export async function countSentConnectionRequests(
  eventId: string,
  requesterId: string
): Promise<number> {
  const { count, error } = await supabase
    .from('connection_requests')
    .select('id', { count: 'exact', head: true })
    .eq('event_id', eventId)
    .eq('requester_id', requesterId);
  if (error) {
    console.error('[match.service] countSentConnectionRequests error:', error);
    return 0;
  }
  return count ?? 0;
}

export async function listMatches(
  eventId: string,
  userId: string
): Promise<ListMatchesResult> {
  const { data, error } = await supabase
    .from('matches')
    .select('*')
    .eq('event_id', eventId)
    .or(`user_a_id.eq.${userId},user_b_id.eq.${userId}`)
    .order('created_at', { ascending: false });

  return { data: data ?? [], error };
}

export async function listMatchesWithProfiles(
  eventId: string,
  userId: string
): Promise<MatchWithProfile[]> {
  const { data, error } = await supabase
    .from('matches')
    .select('id, event_id, user_a_id, user_b_id, created_at, user_a:users!matches_user_a_id_fkey(name, role, one_liner, is_premium), user_b:users!matches_user_b_id_fkey(name, role, one_liner, is_premium)')
    .eq('event_id', eventId)
    .or(`user_a_id.eq.${userId},user_b_id.eq.${userId}`)
    .order('created_at', { ascending: false });
  if (error) {
    console.error('[match.service] listMatchesWithProfiles error:', error);
    return [];
  }
  return (data ?? []).map((row: any) => {
    const isA = row.user_a_id === userId;
    const other = isA ? row.user_b : row.user_a;
    return {
      id: row.id,
      event_id: row.event_id,
      other_user_id: isA ? row.user_b_id : row.user_a_id,
      other_name: other?.name ?? null,
      other_role: other?.role ?? null,
      other_one_liner: other?.one_liner ?? null,
      other_is_premium: !!other?.is_premium,
      created_at: row.created_at,
    };
  });
}

export function getPostEventSummaryStub(input: PostEventSummaryInput): string {
  const { eventName, userName, matches } = input;
  const matchCount = matches.length;
  const greeting = `Hi ${userName || 'there'},`;
  const intro = matchCount === 0
    ? `Thanks for attending ${eventName}! You didn't make any mutual connections this time — but your profile is ready for the next event.`
    : `Thanks for attending ${eventName}! You made ${matchCount} mutual connection${matchCount === 1 ? '' : 's'}.`;
  const matchLines = matches
    .map((match, index) => {
      const name = match.matchedUserName ?? 'Someone';
      const role = match.matchedUserRole ? ` (${match.matchedUserRole})` : '';
      const date = new Date(match.matchedAt).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
      });
      return `  ${index + 1}. ${name}${role} — matched on ${date}`;
    })
    .join('\n');
  const body = matchCount > 0
    ? `\nYour connections:\n${matchLines}\n\nReach out while the event is still fresh!`
    : '';
  const footer = `\nThis summary was generated by Beacon. You received this because you attended ${eventName}.\n`;
  return [greeting, '', intro, body, footer].join('\n');
}

/**
 * Atomically authorizes the signal, consumes one scarce signal, inserts the
 * connection request, and detects a reciprocal mutual. The requester ID is
 * retained in the signature for existing callers, but database auth.uid() is
 * the source of truth.
 */
export async function sendConnectionRequest(
  eventId: string,
  requesterId: string,
  recipientId: string
): Promise<SendConnectionRequestResult> {
  if (!eventId || !requesterId || !recipientId) {
    return { request: null, match: null, error: { message: 'Event and participants are required.' } };
  }

  const { data, error } = await supabase
    .rpc('secure_send_connection_request', {
      p_event_id: eventId,
      p_recipient_id: recipientId,
      p_nonce: createIdempotencyNonce(),
    })
    .single();

  if (error || !data) {
    const message = error?.message?.includes('Signal budget exhausted')
      ? 'You have used every high-intent signal for this event.'
      : error?.message ?? 'Failed to send connection request.';
    console.error('[match.service] secure_send_connection_request error:', error);
    return { request: null, match: null, error: { message } };
  }

  const row = data as SecureConnectionResultRow;
  const request: ConnectionRequestRow = {
    id: row.request_id,
    event_id: row.request_event_id,
    requester_id: row.requester_id,
    recipient_id: row.recipient_id,
    status: row.request_status,
    created_at: row.request_created_at,
  };

  const match: MatchRow | null = row.match_id && row.match_event_id && row.match_user_a_id && row.match_user_b_id && row.match_created_at
    ? {
        id: row.match_id,
        event_id: row.match_event_id,
        user_a_id: row.match_user_a_id,
        user_b_id: row.match_user_b_id,
        created_at: row.match_created_at,
      }
    : null;

  return {
    request,
    match,
    remainingSignalBudget: row.remaining_signal_budget,
    error: null,
  };
}
