// =============================================================================
// Beacon MVP — Database Types
// profile_scope: global | auth_method: otp
// Generated by: Beacon MVP Scaffold Generator
// =============================================================================

// ─── Primitive Aliases ────────────────────────────────────────────────────────
export type Timestamp = string; // ISO-8601 UTC string from Supabase
export type UUID = string;

// ─── Enums ────────────────────────────────────────────────────────────────────
export type RequestStatus = 'pending' | 'withdrawn';
export type LocationType = 'live' | 'fixed';
export type ParticipantStatus = 'pending' | 'approved' | 'rejected';

// ─── Row Interfaces ────────────────────────────────────────────────────────────

/**
 * users table
 * profile_scope = "global": name, role, one_liner live here (shared across events)
 */
export interface UserRow {
  id: UUID;
  email: string;
  name: string | null;
  role: string | null;
  one_liner: string | null;
  is_premium: boolean;
  premium_since: Timestamp | null;
  is_discoverable: boolean;
  last_known_lat: number | null;
  last_known_lng: number | null;
  last_location_at: Timestamp | null;
  created_at: Timestamp;
  updated_at: Timestamp;
}

/** Returned by get_nearby_premium RPC */
export interface NearbyPremiumUser {
  user_id: UUID;
  name: string | null;
  role: string | null;
  one_liner: string | null;
  latitude: number;
  longitude: number;
  distance_m: number;
  bearing_deg: number;
  last_seen_at: Timestamp;
}

export interface EventRow {
  id: UUID;
  host_id: UUID;
  name: string;
  description: string | null;
  join_code: string;
  location_type: LocationType;
  latitude: number | null;
  longitude: number | null;
  address: string | null;
  requires_approval: boolean;
  access_code: string | null;
  show_participant_count: boolean;
  starts_at: Timestamp | null;
  ends_at: Timestamp | null;
  finalized_at: Timestamp | null;
  created_at: Timestamp;
}

/**
 * event_participants table
 * profile_scope = "global": no profile columns here — they live on UserRow
 */
export interface EventParticipantRow {
  id: UUID;
  event_id: UUID;
  user_id: UUID;
  status: ParticipantStatus;
  joined_at: Timestamp;
}

export interface ConnectionRequestRow {
  id: UUID;
  event_id: UUID;
  requester_id: UUID;
  recipient_id: UUID;
  status: RequestStatus;
  created_at: Timestamp;
}

export interface MatchRow {
  id: UUID;
  event_id: UUID;
  user_a_id: UUID;
  user_b_id: UUID;
  created_at: Timestamp;
}

// ─── Social feed ────────────────────────────────────────────────────────────

export interface PostRow {
  id: UUID;
  author_id: UUID;
  event_id: UUID | null;
  body: string;
  image_path: string | null;
  created_at: Timestamp;
  updated_at: Timestamp;
}

export interface FollowRow {
  follower_id: UUID;
  followed_id: UUID;
  created_at: Timestamp;
}

export interface PostLikeRow {
  post_id: UUID;
  user_id: UUID;
  created_at: Timestamp;
}

/** Denormalized post row from get_home_feed / get_event_feed / get_user_posts */
export interface FeedPost {
  id: UUID;
  author_id: UUID;
  event_id: UUID | null;
  body: string;
  image_path: string | null;
  created_at: Timestamp;
  author_name: string | null;
  author_role: string | null;
  author_is_premium: boolean;
  like_count: number;
  viewer_liked: boolean;
}

// ─── Insert / Update Payload Types ───────────────────────────────────────────

export type UserInsert = Omit<UserRow, 'created_at' | 'updated_at'>;
export type UserUpdate = Partial<
  Pick<
    UserRow,
    | 'name'
    | 'role'
    | 'one_liner'
    | 'is_discoverable'
    | 'last_known_lat'
    | 'last_known_lng'
    | 'last_location_at'
  >
>;

export type EventInsert = Omit<EventRow, 'id' | 'created_at' | 'join_code' | 'finalized_at'>;
export type EventUpdate = Partial<Omit<EventRow, 'id' | 'host_id' | 'created_at' | 'join_code' | 'finalized_at'>>;

export type EventParticipantInsert = Pick<
  EventParticipantRow,
  'event_id' | 'user_id'
>;
export type EventParticipantUpdate = Pick<EventParticipantRow, 'status'>;

export type ConnectionRequestInsert = Pick<
  ConnectionRequestRow,
  'event_id' | 'requester_id' | 'recipient_id'
>;
export type ConnectionRequestUpdate = Pick<ConnectionRequestRow, 'status'>;

// ─── Composite / View Types ───────────────────────────────────────────────────

/** Returned by detect_mutual_match RPC */
export interface MutualMatchResult {
  id: UUID;
  event_id: UUID;
  user_a_id: UUID;
  user_b_id: UUID;
  created_at: Timestamp;
}

/** Flattened participant shown on the Discover screen */
export interface DiscoverableParticipant {
  participant_id: UUID;
  user_id: UUID;
  event_id: UUID;
  status: ParticipantStatus;
  joined_at: Timestamp;
  email: string | null;
  name: string | null;
  role: string | null;
  one_liner: string | null;
  is_premium: boolean;
}

/** Flattened pending request shown on host management */
export interface PendingJoinRequest {
  participant_id: UUID;
  user_id: UUID;
  event_id: UUID;
  joined_at: Timestamp;
  name: string | null;
  email: string | null;
  role: string | null;
  one_liner: string | null;
}

export interface EventWithHost {
  event: EventRow;
  host: UserRow | null;
}

// ─── Database Shape (Supabase generic) ────────────────────────────────────────

export interface Database {
  public: {
    Tables: {
      users: {
        Row: UserRow;
        Insert: UserInsert;
        Update: UserUpdate;
      };
      events: {
        Row: EventRow;
        Insert: EventInsert;
        Update: EventUpdate;
      };
      event_participants: {
        Row: EventParticipantRow;
        Insert: EventParticipantInsert;
        Update: EventParticipantUpdate;
      };
      connection_requests: {
        Row: ConnectionRequestRow;
        Insert: ConnectionRequestInsert;
        Update: ConnectionRequestUpdate;
      };
      matches: {
        Row: MatchRow;
        Insert: never; // SECURITY DEFINER function only
        Update: never;
      };
      posts: {
        Row: PostRow;
        Insert: Pick<PostRow, 'author_id' | 'event_id' | 'body' | 'image_path'>;
        Update: Partial<Pick<PostRow, 'body' | 'image_path'>>;
      };
      follows: {
        Row: FollowRow;
        Insert: FollowRow;
        Update: never;
      };
      post_likes: {
        Row: PostLikeRow;
        Insert: PostLikeRow;
        Update: never;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
