// =============================================================================
// Beacon MVP — Database Types
// profile_scope: global | auth_method: otp
// Generated by: Beacon MVP Scaffold Generator
// =============================================================================

// ─── Primitive Aliases ────────────────────────────────────────────────────────
export type Timestamp = string; // ISO-8601 UTC string from Supabase
export type UUID = string;

// ─── Enums ────────────────────────────────────────────────────────────────────
export type RequestStatus = 'pending' | 'withdrawn';
export type LocationType = 'live' | 'fixed';
export type ParticipantStatus = 'pending' | 'approved' | 'rejected';

// ─── Row Interfaces ───────────────────────────────────────────────────────────

/**
 * users table
 * profile_scope = "global": name, role, one_liner live here (shared across events)
 */
export interface UserRow {
  id: UUID;
  email: string;
  name: string | null;
  role: string | null;
  one_liner: string | null;
  created_at: Timestamp;
  updated_at: Timestamp;
}

export interface EventRow {
  id: UUID;
  host_id: UUID;
  name: string;
  description: string | null;
  join_code: string;
  location_type: LocationType;
  latitude: number | null;
  longitude: number | null;
  address: string | null;
  requires_approval: boolean;
  access_code: string | null;
  show_participant_count: boolean;
  starts_at: Timestamp | null;
  ends_at: Timestamp | null;
  created_at: Timestamp;
}

/**
 * event_participants table
 * profile_scope = "global": no profile columns here — they live on UserRow
 */
export interface EventParticipantRow {
  id: UUID;
  event_id: UUID;
  user_id: UUID;
  status: ParticipantStatus;
  joined_at: Timestamp;
}

export interface ConnectionRequestRow {
  id: UUID;
  event_id: UUID;
  requester_id: UUID;
  recipient_id: UUID;
  status: RequestStatus;
  created_at: Timestamp;
}

export interface MatchRow {
  id: UUID;
  event_id: UUID;
  user_a_id: UUID;
  user_b_id: UUID;
  created_at: Timestamp;
}

// ─── Insert / Update Payload Types ───────────────────────────────────────────

export type UserInsert = Omit<UserRow, 'created_at' | 'updated_at'>;
export type UserUpdate = Partial<Pick<UserRow, 'name' | 'role' | 'one_liner'>>;

export type EventInsert = Omit<EventRow, 'id' | 'created_at' | 'join_code'>;
export type EventUpdate = Partial<Omit<EventRow, 'id' | 'host_id' | 'created_at' | 'join_code'>>;

export type EventParticipantInsert = Pick<
  EventParticipantRow,
  'event_id' | 'user_id'
>;
export type EventParticipantUpdate = Pick<EventParticipantRow, 'status'>;

export type ConnectionRequestInsert = Pick<
  ConnectionRequestRow,
  'event_id' | 'requester_id' | 'recipient_id'
>;
export type ConnectionRequestUpdate = Pick<ConnectionRequestRow, 'status'>;

// ─── Composite / View Types ───────────────────────────────────────────────────

/** Returned by detect_mutual_match RPC */
export interface MutualMatchResult {
  id: UUID;
  event_id: UUID;
  user_a_id: UUID;
  user_b_id: UUID;
  created_at: Timestamp;
}

/** Flattened participant shown on the Discover screen */
export interface DiscoverableParticipant {
  participant_id: UUID;     // event_participants.id
  user_id: UUID;
  event_id: UUID;
  status: ParticipantStatus;
  joined_at: Timestamp;
  // User profile fields (global scope)
  email: string;
  name: string | null;
  role: string | null;
  one_liner: string | null;
}

/** Event with host user information */
export interface EventWithHost {
  event: EventRow;
  host: UserRow;
}

/** Join request pending host approval */
export interface PendingJoinRequest {
  participant_id: UUID;
  user_id: UUID;
  event_id: UUID;
  joined_at: Timestamp;
  // User info
  name: string | null;
  email: string;
  role: string | null;
  one_liner: string | null;
}

/** Returned after a user successfully joins an event */
export interface ActiveEventContext {
  event: EventRow;
  participant: EventParticipantRow;
}

// ─── Database Interface (for createClient<Database> generic) ─────────────────

export interface Database {
  public: {
    Tables: {
      users: {
        Row: UserRow;
        Insert: UserInsert;
        Update: UserUpdate;
      };
      events: {
        Row: EventRow;
        Insert: EventInsert; // hosts can create events
        Update: EventUpdate; // hosts can update their events
      };
      event_participants: {
        Row: EventParticipantRow;
        Insert: EventParticipantInsert;
        Update: EventParticipantUpdate;
      };
      connection_requests: {
        Row: ConnectionRequestRow;
        Insert: ConnectionRequestInsert;
        Update: ConnectionRequestUpdate;
      };
      matches: {
        Row: MatchRow;
        Insert: never; // SECURITY DEFINER function only
        Update: never;
      };
    };
    Functions: {
      detect_mutual_match: {
        Args: {
          p_event_id: UUID;
          p_requester_id: UUID;
          p_recipient_id: UUID;
        };
        Returns: MutualMatchResult[];
      };
      approve_participant_with_code: {
        Args: {
          p_event_id: UUID;
          p_user_id: UUID;
          p_access_code: string;
        };
        Returns: boolean;
      };
    };
    Enums: {
      request_status: RequestStatus;
      location_type: LocationType;
      participant_status: ParticipantStatus;
    };
  };
}
