export const FEATURE_FLAGS = {
  presenceEngine: true,
  spatialField: true,
  spatialOpportunityField: true,
  spatialProgression: true,
  spatialContracts: true,
  spatialDistrict: true,
  regretRecorder: false,
  opportunitySurge: true,
  opportunityWindowBanner: true,
  nextBestAction: false,
  vault: true,
  signalScarcity: true,
  limitedDrops: false,
  invisibleVip: false,
  verifiedRoleGlyphs: false,
  officeHoursQueueQuality: false,
  accessDropWaitlists: false,
  organizerOutcomeIntelligence: false,
  privateBeaconIndex: false,
  sponsorProofSummary: false,
  repeatEventLearning: false,
  securityControlPlane: true,
  adaptiveSecurityRisk: false,
  securityDecisionReceipts: false,
  outcomeHandshakeProtocol: true,
  decisionProvenance: true,
  runtimeReliability: true,
} as const;

export type FeatureFlagKey = keyof typeof FEATURE_FLAGS;
